version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/services/app/Dockerfile
    image: nest-ambassador
    restart: always
    ports:
      - '${PORT}:${PORT}'
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_MAIN_HOST: ${DB_MAIN_HOST:-db}
      DB_MAIN_PORT: ${DB_MAIN_PORT:-3306}
    depends_on:
      - db

  db:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MAIN_PASSWORD:-nestpass}
      MYSQL_USER: ${DB_MAIN_USER:-nest}
      MYSQL_PASSWORD: ${DB_MAIN_PASSWORD:-nestpass}
      MYSQL_DATABASE: ${DB_MAIN_DATABASE:-ambassador}
    volumes:
      - ambassador_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_MAIN_PASSWORD:-nestpass}
    ports:
      - 8181:80
    depends_on:
      - db

volumes:
  ambassador_data:
    driver: local
